baseURL = 'http://example.org/'
languageCode = 'fr'
title = 'Alexandre Mimms - Carnet de thèse'

theme = "paper"


[params]
  # color style
  color = 'linen'                   # linen, wheat, gray, light

  # header social icons
  instagram = '_alexmimms'   # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                        # show rss icon

  # home page profile
  avatar = 'https://media.licdn.com/dms/image/C5603AQHUG6WqfQJYcg/profile-displayphoto-shrink_800_800/0/1604349153050?e=2147483647&v=beta&t=w1JfauZjKybFg34ewtoR0QeE3qPbYK_MMxMLfSHvYQI'
  name = 'Alexandre Mimms'
  bio = 'Doctorant contractuel - Université Paris II Panthéon Assas'

  # misc
  disableHLJS = true                # disable requesting highlight.js
  monoDarkIcon = true               # show monochrome dark mode icon
