baseURL = 'https://carnetdethese.amimms.fr/'
languageCode = 'fr'
title = 'Carnet de thèse'


DisqusShortname = 'carnetdethese'
enableEmoji = true

[params]
  # color style
  color = 'linen'                   # linen, wheat, gray, light

  # header social icons
  rss = true                        # show rss icon

  # home page profile
  avatar = ''
  name = 'Carnet de thèse'
  bio = 'Chroniques de recherches'
  
  
  
  # misc
  disableHLJS = true                # disable requesting highlight.js
  monoDarkIcon = true               # show monochrome dark mode icon
  
 
  custom_css = ["css/custom.css"]
  
  
[taxonomies]

  author = "authors"
  tag = "tags"
  category = "categories"
  
[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"
